# Generated by Django 2.0 on 2018-08-09 18:50

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(max_length=1000, verbose_name=django.db.models.fields.URLField),
        ),
    ]
