# Generated by Django 2.0 on 2018-08-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20180731_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='user1',
        ),
    ]
