# Generated by Django 2.0 on 2018-08-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0008_remove_post1_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='user',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post1',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
